version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:9.11.2 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - restore_cache:
          keys:
            dependency-cache-{{ checksum "server/package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
      - run:
          name: Install npm packages
          command: cd server && npm install
      - save_cache:
          paths:
            - ./node_modules
          key: dependency-cache-{{ checksum "server/package-lock.json" }}
      - run:
          environment:
            PGHOST: ec2-3-83-125-137.compute-1.amazonaws.com
            PGDATABASE: reviews
            PGPORT: 5432
            PORT: 80
            PGUSER: patrick
            PGPASSWORD: shigity13
          command: cd server && npm test
