version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:9.11.2 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: cd server && npm install
      - run:
          context: database
          environment:
            PGHOST: ec2-3-83-125-137.compute-1.amazonaws.com
            PGDATABASE: reviews
            PGPORT: 5432
            PORT: 80
          command: cd server && npm test
