version: "3.7"
services:
  api:
    image: reviews-api
    build: .
    networks:
      - backend
    environment:
      PORT: 80
    ports:
      - "80:80"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
networks:
  backend:
    driver: bridge
